os: linux
dist: xenial
language: php

php:
  - 7.3
  - 7.4

before_install:
  - git submodule init
  - git submodule update

install:
  - composer install

script:
  - php vendor/bin/psalm
  - php vendor/bin/phpcs
  - php vendor/bin/phpunit

